image: node:4.2.2

variables:
  POSTGRES_DB: postgres

cache:
  untracked: true
  paths:
  - node_modules/

test1:
  script:
   - npm install
   - node ./specs/start.js ./specs/async.spec.js

test2:
  services:
    - postgres:9.5.0
  script:
   - npm install
   - node ./specs/start.js ./specs/db-postgres.spec.js
