stages:
  - test
  - cleanup

app_test:
  stage: test
  script:
    - docker-compose build
    - docker-compose up node
    - exit $(docker-compose ps | grep -c "Exit 1")


cleanup_job:
  stage: cleanup
  script:
    - docker-compose stop
    - docker-compose rm -f
  when: always
