image: node:4.2.2

variables:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: $MY_DB_USER
  POSTGRES_PASSWORD: $MY_DB_PASS

cache:
  untracked: true
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
   - npm install
   - node ./specs/start.js ./specs/async.spec.js
  tags:
    - postgres
    - node

test_db:
  stage: test
  services:
    - postgres:9.5.0
  script:
   - npm install
   - node ./specs/start.js ./specs/db-postgres.spec.js
  tags:
    - postgres
    - node
