image: node:4.2.2

services:
  - postgres:9.5.0

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: MY_DB_USER
  POSTGRES_PASSWORD: MY_DB_PASS

cache:
  untracked: true
  paths:
  - node_modules/

test:
  script:
   - npm install
   - node ./specs/start.js ./specs/async.spec.js
