stages:
- test
- cleanup

before_script:
  - docker-compose build
  - docker-compose up -d

async_test:
  stage: test
  script:
    - docker-compose run --rm --no-deps node /bin/bash ./scripts/docker-tests.sh ./specs/async.spec.js

db_test:
  stage: test
  script:
    - docker-compose run --rm node /bin/bash ./scripts/docker-tests.sh ./specs/db-postgres.spec.js
cleanup_job:
  stage: cleanup
  script:
    - docker-compose stop
    - docker-compose rm -f
  when: always
