image: node:4.2.2

variables:
  POSTGRES_USER: MY_DB_USER
  POSTGRES_PASSWORD: MY_DB_PASS

cache:
  paths:
  - node_modules/

test:
  services:
    - postgres:9.5.0
  script:
   - npm install
   - node ./specs/start.js
